### ISSUE TITLE
v0.2.0 tracking issue

### ISSUE THREAD

**Issue by NotJeremyLiu** [skip-mev/skip-api-contracts#28]
Main Features:
- [x] https://github.com/skip-mev/skip-api-contracts/issues/21
    - [x] https://github.com/skip-mev/skip-api-contracts/pull/27
    - [x] https://github.com/skip-mev/skip-api-contracts/pull/37
    - [x] https://github.com/skip-mev/skip-api-contracts/pull/38
    - [x] https://github.com/skip-mev/skip-api-contracts/pull/39
    - [x] https://github.com/skip-mev/skip-api-contracts/pull/40
    - [x] https://github.com/skip-mev/skip-api-contracts/pull/44

General Improvements:
- [x] https://github.com/skip-mev/skip-api-contracts/pull/26
- [x] https://github.com/skip-mev/skip-api-contracts/pull/29
- [x] https://github.com/skip-mev/skip-api-contracts/pull/30
- [x] https://github.com/skip-mev/skip-api-contracts/pull/31
- [x] https://github.com/skip-mev/skip-api-contracts/pull/32
- [x] https://github.com/skip-mev/skip-api-contracts/pull/33
- [x] https://github.com/skip-mev/skip-api-contracts/pull/34
- [x] https://github.com/skip-mev/skip-api-contracts/pull/35
- [x] https://github.com/skip-mev/skip-api-contracts/pull/36
- [x] https://github.com/skip-mev/skip-api-contracts/pull/42
- [x] https://github.com/skip-mev/skip-api-contracts/pull/47

Audit Improvements:
- [x] https://github.com/skip-mev/skip-api-contracts/pull/19

Chores:
- [x] https://github.com/skip-mev/skip-api-contracts/pull/50
- [x] https://github.com/skip-mev/skip-api-contracts/pull/51

Deployment:
- [x] Deploy new contracts to testnet (https://github.com/skip-mev/skip-api-contracts/pull/48)
- [x] Deploy new contracts to mainnet (https://github.com/skip-mev/skip-api-contracts/pull/48)

Total Interface Changes:
1. `PostSwapAction` type renamed to `Action` (https://github.com/skip-mev/skip-api-contracts/pull/26)
2. Optional `refund_address` field added to `SwapExactCoinOut` (https://github.com/skip-mev/skip-api-contracts/pull/27)
3. `coin_in` removed from `SwapExactCoinIn` type (https://github.com/skip-mev/skip-api-contracts/pull/31)
4. `fee` changed from a required field (`IbcFee`) to an optional field (`Option<IbcFee>`) (https://github.com/skip-mev/skip-api-contracts/pull/35)
5. `coin_out` removed from `SwapExactCoinOut` type (https://github.com/skip-mev/skip-api-contracts/pull/36) 
6. `user_swap` param in entry point's `swap_and_action` changed from type `SwapExactCoinIn` to an enum type `Swap`, with two variants: `SwapExactCoinOut` and `SwapExactCoinIn`

Non-Interface Changing But User Impactful Logic Changes:
- Affiliate fee BPS are now applied on the `min_coin` and not the coin received from the swap. This is to allow the affiliate fee logic to be standardized for the user swap for both `SwapExactCoinIn` and `SwapExactCoinOut`

**Comment by NotJeremyLiu** [comment]
@wllmshao @zrbecker This issue is tracking all the changes I want to make for our next contract release. I merged in many changes in the general improvements category (thinking they were uncontroversial and internal quality of life/code changes), but realized anything that is interface changing can/may be controversial.

I've listed all the interface changes in Total Interface Changes and the associated PR with them, when you have time would be great to view the changes and call out if you disagree with any.

Anything can be changed, regardless if they have been merged already, so if you'd like to review all the general improvement PRs please feel free to do so.

The changes listed without PRs linked do not have PRs ready for them yet.
